### ISSUE TITLE
Missing files in utils folder?

### ISSUE THREAD

**Issue by dunglt2015** [ziwei-zh/CorrPM#2]
Thank for publish your code, 

I try to run ./run_train.sh, but face this error. I cannot find this files in utils folder. Does your class CriterionPoseEdge different from class CriterionAll in CE2P repo?
> Traceback (most recent call last):
>   File "train.py", line 24, in <module>
>     from utils.criterion import CriterionPoseEdge
> ImportError: cannot import name 'CriterionPoseEdge'

**Comment by ziwei-zh** [comment]
Thanks for correction. I put the criterion.py into ```utils``` folder and update the code in some other files. You can renew the project in your terminal.
The class CriterionPoseEdge is different from  class CriterionAll since we add the losses for **edge** and **pose**.
If there are other problems, please feel free to contact me.
